# Generated by Django 4.0.5 on 2022-06-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceHTTP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'verbose_name': 'Улица', 'verbose_name_plural': 'Улицы'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_shop', to='serviceHTTP.city'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_street', to='serviceHTTP.street'),
        ),
        migrations.AlterField(
            model_name='street',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='street_city', to='serviceHTTP.city'),
        ),
    ]
